apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: vcluster
    repo: https://charts.loft.sh
    version: 0.25.1
    releaseName: dev-test
    namespace: dev-test
    valuesFile: vcluster-values.yaml
resources: []
