apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub-stage
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  source:
    repoURL: https://github.com/Alwin-K-Thomas/vcluster-jupyterhub.git
    chart: jupyterhub
    targetRevision: 3.3.7
    helm:
      valueFiles:
        - apps/jupyterhub/overlays/stage/values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
