apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyer-prod
  namespace: argocd
spec:
  source:
    repoURL:
    path: apps/jupyterhub/overlays/prod
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
